### ISSUE TITLE
Infinite loading of audio bank

### ISSUE THREAD

**Issue by LiamDormon** [MRV6/mp_insidetrack#1]
I'm on build 2060 and the script gets stuck infinitely loading on this
```lua
while not RequestScriptAudioBank('DLC_VINEWOOD/CASINO_GENERAL') do
    Wait(0)
end
 ```
 Removing this line resolve the problem the scaleforms work but without any audio.

**Comment by MRV6** [comment]
Thanks for your feedback, however it seems to works fine on b2060 and b2189, are you sure that the b2060 is enabled ?

**Comment by LiamDormon** [comment]
Yes, all of the scaleforms, IPLs etc for it are loading just fine, b2060 (canary) watermark in the corner and cars and clothing work so it's definately enabled. The only problem is this RequestScriptAudioBank native.

**Comment by MRV6** [comment]
Do you have some audio banks loaded ?

**Comment by LiamDormon** [comment]
No

**Comment by MRV6** [comment]
Hm, that's pretty weird. I can't even reproduce the bug, also, no one reported it so that's probably a you problem.

**Comment by MRV6** [comment]
Can you try on a clean server ?

**Comment by MRV6** [comment]
Alright, i will mark this as invalid and see if other people report this issue.
