### ISSUE TITLE
Sound after race finishes does not stop

### ISSUE THREAD

**Issue by RnYPT** [MRV6/mp_insidetrack#2]
So, some times when the race finishes the "ambient sound" does not stop, the sound only drops to like 50% of volume, i tried to add a StopSound(0) in client.lua in like 89 but with no luck, can you try and fix this?

**Comment by RnYPT** [comment]
Btw im in this build "+set sv_enforceGameBuild 2189"

**Comment by RnYPT** [comment]
https://streamable.com/jlqoyb

**Comment by MRV6** [comment]
Hello, thanks for your feedback. I will try to reproduce this bug.

**Comment by MRV6** [comment]
Hopefully fixed in https://github.com/MRV6/mp_insidetrack/commit/86d868642d04b9f2d290924eb20a21462eb93695, can you try now ?

**Comment by MRV6** [comment]
Hopefully fixed with the last two commits (86d868642d04b9f2d290924eb20a21462eb93695 & 8480fe6ac89d1dfb85ff8eda4b5fe9e37c840bfd), can you try now ?

**Comment by MRV6** [comment]
Hopefully fixed, can you try now ?

**Comment by gunsela92** [comment]
Still bugging. I tried but after some races, its bugging. And games are duplicating. For example : I integrated removemoney function and if its bugged the money is removing 3 or 4 times. And sounds are duplicating to. (Btw i tried without removemoney function too its not the problem)

**Comment by MRV6** [comment]
This time I can't reproduce the bug, it seems definitely fixed. Are you sure that you updated the resource ?

**Comment by gunsela92** [comment]
Yeah i downloaded from the beginning but its happening after 10-15 games.

**Comment by MRV6** [comment]
« downloaded from the beginning » ?

**Comment by gunsela92** [comment]
I mean downloaded the last version. Discarded my modifications of givemoney and removemoney events.

**Comment by MRV6** [comment]
That's pretty weird because I can't reproduce this bug anymore, i will continue to try.

**Comment by MRV6** [comment]
I still can't reproduce the issue, it seems like that I definitely fixed it the last time. Also the guy who opened the issue didn't even answer so I can't do much.
