### ISSUE TITLE
No scaleform

### ISSUE THREAD

**Issue by Warlif** [MRV6/mp_insidetrack#5]
Hi, got a problem. When i write /itrack, nothing happen. I got a freeze screen, and can't do anything. No error in console.

**Comment by MRV6** [comment]
Hey, looks like you aren't using 2060 or above game build.

**Comment by Warlif** [comment]
> Hey, looks like you aren't using 2060 or above game build.

I'm using 2189 game build for cayo perico so it's not the problem

**Comment by MRV6** [comment]
Do you have the latest version ? Also, try to put a print in the scaleform loading loop and see what happens.
