### ISSUE TITLE
Multiplayer Main Event not working?

### ISSUE THREAD

**Issue by BTNGaming** [MRV6/mp_insidetrack#6]
Main Event "Play with others" never works, countdown just counts from 60 seconds and then restarts. Can only do Single events. I might be an idiot, but is this just not setup, or is this something I'm doing wrong?

**Comment by MRV6** [comment]
Not implemented yet, I don't have much time for that but I already created a branch (`main-event`). Feel free to contribute if you want, not sure when I will do it.
